name: MLflow CI Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - "MLProject/**"
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/reehandn/adult-mlflow.mlflow/
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USER }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Set up job
      run: echo "Starting MLflow CI Pipeline"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Check environment
      run: |
        python --version
        pip --version

    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 dagshub pandas numpy scikit-learn joblib

    - name: Run MLflow Project
      run: |
        mlflow run MLProject \
          --env-manager=local \
          --experiment-name "Adult_Income_Basic" \
          -P max_iter=1000

    - name: Read Run ID
      run: |
        echo "RUN_ID=$(cat MLProject/run_id.txt)" >> $GITHUB_ENV

    - name: Download MLflow Model Artifacts
      run: |
        mkdir -p downloaded_model
        mlflow artifacts download --run-id ${{ env.RUN_ID }} --artifact-path model --dst-path downloaded_model

    - name: Upload Model Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
          name: model-artifact-${{ env.RUN_ID }}
          path: downloaded_model/model

    - name: Build Docker Image
      run: |
        mlflow models build-docker \
          -m "runs:/${{ env.RUN_ID }}/model" \
          -n username/adult-income-mlflow

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Tag Docker Image
      run: |
        docker tag username/adult-income-mlflow:latest \
                   username/adult-income-mlflow:${{ env.RUN_ID }}

    - name: Push Docker Image
      run: |
        docker push username/adult-income-mlflow:latest
        docker push username/adult-income-mlflow:${{ env.RUN_ID }}

    - name: Complete job
      run: echo "MLflow CI Pipeline Completed"
